import { createHash } from "node:crypto";
import type Database from "better-sqlite3";
import type { Promesa, PromesaAtomicUpdateInput, PromesaCreateInput, PromesaLegacyInput, PromesaLegacyMigrationResult, PromesaMutationResult, PromesaState, PromesaUpdateInput } from "../../src/types/api.types";

type Origin = Promesa['origen'];
const STATES: readonly PromesaState[] = ['PENDIENTE','CUMPLIDA','CUMPLIDA_PARCIAL','INCUMPLIDA','CANCELADA','REPROGRAMADA'];
const TRANSITIONS: Record<PromesaState, readonly PromesaState[]> = {PENDIENTE:['CUMPLIDA','CUMPLIDA_PARCIAL','INCUMPLIDA','CANCELADA','REPROGRAMADA'],CUMPLIDA:[],CUMPLIDA_PARCIAL:['CUMPLIDA','INCUMPLIDA','CANCELADA','REPROGRAMADA'],INCUMPLIDA:['REPROGRAMADA'],CANCELADA:[],REPROGRAMADA:[]};
const validDate=(value:unknown)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(value)&&!Number.isNaN(Date.parse(value));
function money(value:unknown,defaultValue?:number):number|null{if(value===undefined&&defaultValue!==undefined)return defaultValue;if(typeof value!=='number'||!Number.isFinite(value))return null;return value;}
const owns=(value:object,key:string)=>Object.prototype.hasOwnProperty.call(value,key);
function validateProvidedMoney(input:object):string|null{
  if(owns(input,'monto_prometido')){const value=(input as {monto_prometido?:unknown}).monto_prometido;if(typeof value!=='number'||!Number.isFinite(value)||value<=0)return 'monto_prometido inválido';}
  if(owns(input,'monto_pagado')){const value=(input as {monto_pagado?:unknown}).monto_pagado;if(typeof value!=='number'||!Number.isFinite(value)||value<0)return 'monto_pagado inválido';}
  return null;
}
function deriveCompletedPayment<T extends PromesaCreateInput>(value:T,provided:object,state:PromesaState):T{
  return state==='CUMPLIDA'&&!owns(provided,'monto_pagado')?{...value,monto_pagado:value.monto_prometido}:value;
}
function validate(input:PromesaCreateInput,state:PromesaState):string|null{
  if(!String(input.cliente??'').trim())return 'cliente requerido';if(!validDate(input.fecha_promesa))return 'fecha_promesa inválida';
  const promised=money(input.monto_prometido),paid=money(input.monto_pagado,0);if(promised===null||paid===null||promised<=0||paid<0||paid>promised)return 'montos inválidos';
  if(state==='PENDIENTE'&&paid!==0)return 'PENDIENTE no admite monto pagado';if(state==='CUMPLIDA'&&paid!==promised)return 'CUMPLIDA requiere pago total';if(state==='CUMPLIDA_PARCIAL'&&!(paid>0&&paid<promised))return 'CUMPLIDA_PARCIAL requiere pago parcial';
  if((state==='INCUMPLIDA'||state==='CANCELADA'||state==='REPROGRAMADA')&&paid!==0)return `${state} no admite monto pagado`;if(input.fecha_pago&&!validDate(input.fecha_pago))return 'fecha_pago inválida';if(state==='PENDIENTE'&&input.fecha_pago)return 'PENDIENTE no admite fecha de pago';return null;
}
export function getPromesaById(db:Database.Database,id:number):Promesa|undefined{return db.prepare(`SELECT p.*,COALESCE((SELECT razon_social FROM documentos d WHERE d.cliente=p.cliente LIMIT 1),p.cliente) razon_social FROM promesas p WHERE p.id=?`).get(id) as Promesa|undefined;}
function event(db:Database.Database,id:number,type:string,from:PromesaState|null,to:PromesaState|null,metadata:unknown={}){db.prepare(`INSERT INTO promesa_eventos(promesa_id,tipo_evento,estado_anterior,estado_nuevo,metadata) VALUES(?,?,?,?,?)`).run(id,type,from,to,JSON.stringify(metadata));}
function changed(before:Promesa,after:Record<string,unknown>){const result:Record<string,{anterior:unknown;nuevo:unknown}>={};for(const key of ['fecha_promesa','monto_prometido','monto_pagado','fecha_pago','motivo_incumplimiento','observacion'])if(before[key as keyof Promesa]!==after[key])result[key]={anterior:before[key as keyof Promesa]??null,nuevo:after[key]??null};return result;}
function insertPromesa(db:Database.Database,input:PromesaCreateInput,origin:Origin,eventType:string):PromesaMutationResult{
  const state=input.estado??'PENDIENTE';if(!STATES.includes(state))return{ok:false,code:'PROMESA_INVALID',message:'Estado inválido.'};const providedMoneyReason=validateProvidedMoney(input);if(providedMoneyReason)return{ok:false,code:'PROMESA_INVALID',message:providedMoneyReason};const normalized=deriveCompletedPayment(input,input,state);const reason=validate(normalized,state);if(reason)return{ok:false,code:'PROMESA_INVALID',message:reason};
  const result=db.prepare(`INSERT INTO promesas(cliente,gestion_id,documento_id,fecha_promesa,monto_prometido,monto_pagado,estado,fecha_pago,motivo_incumplimiento,observacion,origen) VALUES(@cliente,@gestion_id,@documento_id,@fecha_promesa,@monto_prometido,@monto_pagado,@estado,@fecha_pago,@motivo_incumplimiento,@observacion,@origen)`).run({cliente:String(normalized.cliente).trim(),gestion_id:normalized.gestion_id??null,documento_id:normalized.documento_id??null,fecha_promesa:normalized.fecha_promesa,monto_prometido:normalized.monto_prometido,monto_pagado:normalized.monto_pagado??0,estado:state,fecha_pago:normalized.fecha_pago||null,motivo_incumplimiento:normalized.motivo_incumplimiento||null,observacion:normalized.observacion||null,origen:origin});
  const id=Number(result.lastInsertRowid);event(db,id,eventType,null,state,{origen:origin});return{ok:true,promesa:getPromesaById(db,id)!};
}
export function createPromesa(db:Database.Database,input:PromesaCreateInput):PromesaMutationResult{return db.transaction(()=>insertPromesa(db,input,'NATIVE','PROMESA_CREADA'))();}
export function listPromesas(db:Database.Database):Promesa[]{return db.prepare(`SELECT p.*,COALESCE((SELECT razon_social FROM documentos d WHERE d.cliente=p.cliente LIMIT 1),p.cliente) razon_social FROM promesas p ORDER BY p.fecha_promesa,p.id`).all() as Promesa[];}
export function updatePromesaAtomic(db:Database.Database,id:number,input:PromesaAtomicUpdateInput):PromesaMutationResult{return db.transaction(()=>{
  const current=getPromesaById(db,id);if(!current)return{ok:false as const,code:'PROMESA_NOT_FOUND' as const,message:'La promesa no existe.'};const providedMoneyReason=validateProvidedMoney(input);if(providedMoneyReason)return{ok:false as const,code:'PROMESA_INVALID' as const,message:providedMoneyReason};const state=input.estado??current.estado;if(!STATES.includes(state))return{ok:false as const,code:'PROMESA_INVALID' as const,message:'Estado inválido.'};if(state!==current.estado&&!TRANSITIONS[current.estado].includes(state))return{ok:false as const,code:'PROMESA_INVALID_TRANSITION' as const,message:`Transición ${current.estado} → ${state} no permitida.`};
  const merged=deriveCompletedPayment({...current,...input,estado:state},input,state);if(state==='CUMPLIDA')merged.fecha_pago=merged.fecha_pago||new Date().toISOString().slice(0,10);const reason=validate(merged,state);if(reason)return{ok:false as const,code:'PROMESA_INVALID' as const,message:reason};const fieldChanges=changed(current,merged);const stateChanged=state!==current.estado;if(!stateChanged&&Object.keys(fieldChanges).length===0)return{ok:true as const,promesa:current};
  db.prepare(`UPDATE promesas SET fecha_promesa=@fecha_promesa,monto_prometido=@monto_prometido,monto_pagado=@monto_pagado,estado=@estado,fecha_pago=@fecha_pago,motivo_incumplimiento=@motivo_incumplimiento,observacion=@observacion,actualizado_en=datetime('now','localtime') WHERE id=@id`).run({...merged,id});if(Object.keys(fieldChanges).length)event(db,id,'PROMESA_EDITADA',current.estado,state,{changes:fieldChanges});if(stateChanged)event(db,id,'PROMESA_ESTADO_CAMBIADO',current.estado,state);return{ok:true as const,promesa:getPromesaById(db,id)!};
})();}
export function updatePromesa(db:Database.Database,id:number,input:PromesaUpdateInput):PromesaMutationResult{return updatePromesaAtomic(db,id,input);}
export function changePromesaState(db:Database.Database,id:number,state:PromesaState,data:PromesaUpdateInput={}):PromesaMutationResult{return updatePromesaAtomic(db,id,{...data,estado:state});}
export function unlinkPromesaFromGestion(db:Database.Database,gestionId:number):number|null{const linked=db.prepare('SELECT id FROM promesas WHERE gestion_id=?').get(gestionId) as {id:number}|undefined;if(!linked)return null;db.prepare("UPDATE promesas SET gestion_id=NULL,actualizado_en=datetime('now','localtime') WHERE id=?").run(linked.id);event(db,linked.id,'PROMESA_GESTION_DESVINCULADA',null,null,{changes:{gestion_id:{anterior:gestionId,nuevo:null}},reason:'GESTION_DELETED'});return linked.id;}
export function migrateHistoricalPromises(db:Database.Database):number{const rows=db.prepare(`SELECT * FROM gestiones WHERE resultado IN ('Promesa de Pago','Promesa Cumplida') AND TRIM(COALESCE(cliente,''))<>'' AND date(fecha_promesa) IS NOT NULL AND monto_promesa>0`).all() as Array<Record<string,unknown>>;return db.transaction(()=>{let inserted=0;for(const row of rows){if(db.prepare('SELECT 1 FROM promesas WHERE gestion_id=?').get(row.id))continue;const state:PromesaState=row.resultado==='Promesa Cumplida'?'CUMPLIDA':'PENDIENTE';const result=insertPromesa(db,{cliente:String(row.cliente),gestion_id:Number(row.id),fecha_promesa:String(row.fecha_promesa),monto_prometido:Number(row.monto_promesa),monto_pagado:state==='CUMPLIDA'?Number(row.monto_promesa):0,estado:state,fecha_pago:null,observacion:typeof row.observacion==='string'?row.observacion:null},'MIGRATED_GESTION','PROMESA_MIGRADA');if(result.ok)inserted++;}return inserted;})();}
export function canonicalizeLegacyPromise(value:PromesaLegacyInput){const state=value.estado??'PENDIENTE';const normalized=deriveCompletedPayment(value,value,state);return{cliente:String(normalized.cliente).trim(),fecha_promesa:String(normalized.fecha_promesa),monto_prometido:normalized.monto_prometido,monto_pagado:normalized.monto_pagado??0,estado:state,fecha_pago:normalized.fecha_pago||null,motivo_incumplimiento:normalized.motivo_incumplimiento||null,observacion:normalized.observacion||null};}
export function hashLegacyPromise(value:PromesaLegacyInput){return createHash('sha256').update(JSON.stringify(canonicalizeLegacyPromise(value))).digest('hex');}
export function migrateLegacyPromises(db:Database.Database,source:string,records:readonly PromesaLegacyInput[]):PromesaLegacyMigrationResult{const mappings:Extract<PromesaLegacyMigrationResult,{ok:true}>['mappings']=[];for(const record of records){const legacyId=String(record.legacy_id??'').trim();if(!legacyId)return{ok:false,code:'PROMESA_INVALID',message:'legacy_id requerido'};const hash=hashLegacyPromise(record);const prior=db.prepare('SELECT promesa_id,payload_hash FROM promesa_legacy_migrations WHERE source=? AND legacy_id=?').get(source,legacyId) as {promesa_id:number;payload_hash:string}|undefined;if(prior){if(prior.payload_hash!==hash)return{ok:false,code:'PROMESA_LEGACY_ID_CONFLICT',legacy_id:legacyId,message:'Payload legacy modificado.'};if(!getPromesaById(db,prior.promesa_id))return{ok:false,code:'PROMESA_LEGACY_MAPPING_ORPHAN',legacy_id:legacyId,message:'El mapping legacy apunta a una promesa inexistente.'};mappings.push({legacy_id:legacyId,promesa_id:prior.promesa_id,inserted:false});continue;}const migrated=db.transaction(()=>{const created=insertPromesa(db,{...record,gestion_id:null},'MIGRATED_LEGACY','PROMESA_LEGACY_APLICADA');if(created.ok===false)return{ok:false as const,code:created.code,message:created.message};db.prepare(`INSERT INTO promesa_legacy_migrations(source,legacy_id,promesa_id,payload_hash) VALUES(?,?,?,?)`).run(source,legacyId,created.promesa.id,hash);return{ok:true as const,id:created.promesa.id};})();if(migrated.ok===false)return migrated;mappings.push({legacy_id:legacyId,promesa_id:migrated.id,inserted:true});}return{ok:true,mappings};}
